require("prototypes.items.turret")
require("prototypes.recipes.turret-recipe")
require("prototypes.entity.turrets")
require("prototypes.entity.projectiles")
require("prototypes.technology.electric-turret-tech")
require("prototypes.technology.electric-turret-effect-tech")
